services:
  - type: web
    name: ledger-formance
    runtime: image
    image:
      url: ghcr.io/formancehq/ledger:latest
    plan: standard
    envVars:
    - key: POSTGRES_URI
      fromDatabase:
        name: ledger-database
        property: connectionString
    - key: PUBLISHER_HTTP_ENABLED
      value: "true"
    - key: PUBLISHER_TOPIC_MAPPING
      value: "*:https://play.svix.com/view/e_yFLqQidXs1o4y1a4ZXGmOXwITPt"
    region: ohio
    
  - type: web
    name: ledger-formance-dev
    runtime: image
    image:
      url: ghcr.io/formancehq/ledger:latest
    plan: starter
    envVars:
    - key: POSTGRES_URI
      fromDatabase:
        name: ledger-db-dev
        property: connectionString
    region: ohio

databases:
  - name: ledger-database
    plan: basic-1gb
    databaseName: ledger_database
    postgresMajorVersion: "16"
    user: ledger
    region: ohio
    ipAllowList: [] # private connection only
  - name: ledger-db-dev
    plan: basic-1gb
    databaseName: ledger_db_dev
    postgresMajorVersion: "16"
    user: ledger
    region: ohio
    ipAllowList: [] # private connection only
