services:
- type: web
  name: ledger-formance
  runtime: image
  image:
    url: ghcr.io/formancehq/ledger:latest
  plan: starter
  envVars:
  - key: PORT
    value: 3068
  - key: POSTGRES_URI
    fromDatabase:
      name: ledger-database
      property: connectionString
  region: ohio
version: "1"

databases:
  - name: ledger-database
    plan: basic-1gb
    databaseName: ledger-database
    postgresMajorVersion: "16"
    user: ledger
    region: ohio
    ipAllowList: [] # private connection only
